version: '3'

services: 
    
    server1:
        image: simple-http
        hostname: server1
        environment:
          - urls_list=http://server1,http://server2,http://server3
        ports: 
            - 5051:80
        deploy:
            resources:
                limits:
                    memory: 50M
        
    server2:
        image: simple-http
        hostname: server2
        environment:
          - urls_list=http://server1,http://server2,http://server3
        ports: 
            - 5052:80
        deploy:
            resources:
                limits:
                    memory: 50M
        
    server3:
        image: simple-http
        hostname: server3
        environment:
          - urls_list=http://server1,http://server2,http://server3
        ports: 
            - 5053:80
        deploy:
            resources:
                limits:
                    memory: 50M
        